max_width = 80
comment_width = 100
match_block_trailing_comma = true
wrap_comments = true
edition = "2021"
error_on_line_overflow = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true